name: "gestion_de_horarios"
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  cupertino_icons: ^1.0.6
  sqflite_common_ffi: ^2.0.0+1

  # Firebase dependencies
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  http: ^1.2.1
  #Unused cloud_firestore: ^5.0.2 
  #Unused firebase_analytics: ^11.1.0 
  #Unused firebase_storage: ^12.1.0 
  #Unused firebase_messaging: ^15.0.2 
  #Unused firebase_crashlytics: ^4.0.2 #Unused

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
  - assets/service_account.json
  uses-material-design: true
