name: "gestion_de_horarios"
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  cupertino_icons: ^1.0.6
  sqflite_common_ffi: ^2.0.0+1
  http: ^1.2.1
  provider: ^6.0.0
  
  # Firebase dependencies
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_functions: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true