// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_BBCkJZmRXEtnGeFZDRsBCe5WET4C_Q',
    appId: '1:423553983559:web:9fe54b165d2fc013c1bd62',
    messagingSenderId: '423553983559',
    projectId: 'gestion-de-horarios-952de',
    authDomain: 'gestion-de-horarios-952de.firebaseapp.com',
    storageBucket: 'gestion-de-horarios-952de.appspot.com',
    measurementId: 'G-MYWFRHCDD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEpl7QjQOE1p2u5R37r5YX_A_kfk3Daw',
    appId: '1:423553983559:android:1816e4550f4463c9c1bd62',
    messagingSenderId: '423553983559',
    projectId: 'gestion-de-horarios-952de',
    storageBucket: 'gestion-de-horarios-952de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyRBFx3E07XBtCojhzbKAXSLgaB6v9WB0',
    appId: '1:423553983559:ios:1414c5afcee2b4a4c1bd62',
    messagingSenderId: '423553983559',
    projectId: 'gestion-de-horarios-952de',
    storageBucket: 'gestion-de-horarios-952de.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}